#import "@local/tmpltr-lib:1.0.0": editable, editable-block, tmpltr-data, md, get

#let data = tmpltr-data()

#set page(paper: "a4", margin: 2cm)
#set text(font: get(data, "brand.fonts.body", default: "Inter"), size: 12pt)
#show heading: it => heading(it, numbering: "1.", number-align: "left")

#let logo_raw = get(data, "brand.logo", default: get(data, "brand.logos.primary", default: none))
#let logo = if logo_raw == "" { none } else { logo_raw }

#let header() = {
  align(left)[
    #if logo != none {
      image(logo, width: 6cm)
    } else {
      rect(width: 6cm, height: 1cm, stroke: 1pt)
    }
  ]
}

#header()

#v(0.75cm)

#editable(
  "quote.title",
  get(data, "quote.title", default: "Sample Document"),
  type: "text",
  default: "Sample Document",
)

#v(0.2cm)

#editable(
  "quote.subtitle",
  get(data, "quote.subtitle", default: "Generated by tmpltr"),
  type: "text",
  default: "Generated by tmpltr",
)

#v(0.5cm)

#editable-block("blocks.summary", title: "Executive Summary", format: "markdown")[
  #md(get(data, "blocks.summary.content", default: "Add your summary content here."))
]
#v(0.3cm)

#editable-block("blocks.scope", title: "Scope", format: "markdown")[
  #md(get(data, "blocks.scope.content", default: "Describe the scope."))
]
#v(0.3cm)

#editable-block("blocks.timeline", title: "Timeline", format: "markdown")[
  #md(get(data, "blocks.timeline.content", default: "Timeline goes here."))
]
