// Tax Return Summary
// @description: Annual tax summary: income, deductions, refund/owed
// @version: 1.0.0
#import "@local/tmpltr-lib:1.0.0": tmpltr-data, get

#let data = tmpltr-data()
#let g(path, default: "") = get(data, path, default: default)

#let money(x, sym: "$") = {
  let val = float(x)
  let v = calc.round(val, digits: 2)
  let neg = v < 0
  let a = calc.abs(v)
  let i = int(a)
  let c = int(calc.round((a - i) * 100))
  if c == 100 { i = i + 1; c = 0 }
  let s = str(i)
  let out = ""
  let n = s.clusters().len()
  for (k, ch) in s.clusters().enumerate() {
    out = out + ch
    let rem = n - k - 1
    if rem > 0 and calc.rem(rem, 3) == 0 { out = out + "," }
  }
  sym + (if neg { "-" } else { "" }) + out + "." + (if c < 10 { "0" } else { "" }) + str(c)
}

// Configuration
#let accent = rgb("#2c3e50")
#let secondary = rgb("#7f8c8d")
#let status-color = if float(g("summary.refund", default: 0)) > 0 { rgb("#27ae60") } else { rgb("#c0392b") }

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm)
)
#set text(font: "Tinos", size: 10.5pt, lang: "en")

// Header: Authority Info
#grid(columns: (1fr, auto),
  [
    #text(size: 18pt, weight: "bold", fill: accent)[#g("authority.name", default: "Tax Authority")] \
    #text(size: 10pt, fill: secondary)[Official Tax Statement
    #if g("summary.year", default: "") != "" [ · Year #g("summary.year", default: "")] ]
  ],
  align(right)[
    #text(weight: "bold", size: 12pt)[TAX SUMMARY] \
    #text(size: 9pt, fill: secondary)[Form MER-1040-S]
  ]
)

#v(10pt)
#line(length: 100%, stroke: 1pt + accent)
#v(10pt)

// Taxpayer & Authority Details
#grid(columns: (1fr, 1fr), column-gutter: 30pt,
  [
    #text(size: 8pt, weight: "bold", fill: secondary, tracking: 1pt)[TAXPAYER INFORMATION] \
    #v(4pt)
    #text(weight: "bold", size: 11pt)[#g("taxpayer.name", default: "N/A")] \
    #g("taxpayer.address", default: "") \
    #text(size: 9pt, fill: secondary)[TIN: #g("taxpayer.tin", default: "N/A")]
  ],
  [
    #text(size: 8pt, weight: "bold", fill: secondary, tracking: 1pt)[ISSUING AUTHORITY] \
    #v(4pt)
    #g("authority.name", default: "N/A") \
    #g("authority.address", default: "")
  ]
)

#v(20pt)

// Summary Section
#block(
  fill: rgb("#f8f9fa"),
  inset: 15pt,
  radius: 2pt,
  stroke: 0.5pt + gray.lighten(50%)
)[
  #set text(font: "Arimo")
  #grid(columns: (1fr, auto),
    [
      #text(size: 14pt, weight: "bold")[Filing Overview] \
      #text(size: 9pt, fill: secondary)[Status: #g("summary.filing_status", default: "N/A")]
    ],
    align(right)[
      #text(size: 10pt)[Tax Year: #g("summary.year", default: "N/A")]
    ]
  )
  
  #v(10pt)
  
  #table(
    columns: (1fr, auto),
    stroke: none,
    column-gutter: 20pt,
    row-gutter: 8pt,
    [Total Income], [#money(g("summary.total_income", default: 0))],
    [Adjustments], [#money(g("summary.adjustments", default: 0), sym: "-")],
    [#text(weight: "bold")[Taxable Income]], [#text(weight: "bold")[#money(g("summary.taxable_income", default: 0))]],
    table.hline(stroke: 0.5pt + gray.lighten(50%)),
    [Total Tax Withheld], [#money(g("summary.tax_withheld", default: 0))],
    [Calculated Tax Liability], [#money(g("summary.tax_due", default: 0), sym: "-")]
  )
]

#v(20pt)

// Final Result (Refund or Due)
#align(center)[
  #rect(
    stroke: 2pt + status-color,
    inset: 15pt,
    radius: 4pt,
    fill: status-color.lighten(95%)
  )[
    #let label = if float(g("summary.refund", default: 0)) > 0 { "Refund Amount" } else { "Amount Due" }
    #text(size: 10pt, weight: "bold", fill: secondary, upper(label)) \
    #v(4pt)
    #text(size: 24pt, weight: "bold", fill: status-color)[
      #if float(g("summary.refund", default: 0)) > 0 {
        money(g("summary.refund", default: 0))
      } else {
        money(g("summary.tax_due", default: 0), sym: "-")
      }
    ]
  ]
]

#v(20pt)

// Footer/Deadlines
#grid(columns: (1fr, 1fr),
  [
    #text(size: 9pt, weight: "bold")[Payment Deadline] \
    #text(size: 11pt, fill: accent)[#g("summary.payment_deadline", default: "N/A")]
  ],
  align(right)[
    #text(size: 8pt, fill: secondary)[
      This is an automated summary. \
      Please refer to your official mail for legal notices.
    ]
  ]
)

#v(1fr)

#set text(size: 7pt, fill: gray)
#line(length: 100%, stroke: 0.5pt + gray.lighten(50%))
#align(center)[
  Generated by Meridian Revenue Services · Confidential Tax Document · #datetime.today().display("[day].[month].[year]")
]
